<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KapalSeeder extends Seeder
{
    public function run()
    {
        $kapals = [
            [
                'kapal_id' => 'KPL001',
                'nama_kapal' => 'KM Nusantara I',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR001',
                'kapasitas' => 150,
                'pelabuhan_asal' => 'Surabaya',
                'rute_aktif' => 'Surabaya → Bawean',
                'tanggal_registrasi' => '2020-01-15',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Kapal passenger ferry modern',
                'nomor_registrasi' => 'REG-2020-001',
                'tahun_pembuatan' => 2018,
                'panjang_kapal' => 85.50,
                'lebar_kapal' => 18.20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL002',
                'nama_kapal' => 'KM Bahari Kita',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR002',
                'kapasitas' => 200,
                'pelabuhan_asal' => 'Bakauheni',
                'rute_aktif' => 'Bakauheni → Merak',
                'tanggal_registrasi' => '2019-06-20',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Sangat Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Kapal reguler rute Jawa-Sumatera',
                'nomor_registrasi' => 'REG-2019-002',
                'tahun_pembuatan' => 2017,
                'panjang_kapal' => 95.00,
                'lebar_kapal' => 20.50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL003',
                'nama_kapal' => 'KMP Lema',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR003',
                'kapasitas' => 200,
                'pelabuhan_asal' => 'Belawan',
                'rute_aktif' => 'Belawan → Batam → Jakarta',
                'tanggal_registrasi' => '2021-03-10',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Kapal cargo dan penumpang',
                'nomor_registrasi' => 'REG-2021-003',
                'tahun_pembuatan' => 2019,
                'panjang_kapal' => 110.00,
                'lebar_kapal' => 22.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL004',
                'nama_kapal' => 'KMP Rafelia',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR002',
                'kapasitas' => 200,
                'pelabuhan_asal' => 'Padangbai',
                'rute_aktif' => 'Padangbai → Lembar',
                'tanggal_registrasi' => '2020-08-25',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Cukup Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Rute Bali-Lombok',
                'nomor_registrasi' => 'REG-2020-004',
                'tahun_pembuatan' => 2018,
                'panjang_kapal' => 92.00,
                'lebar_kapal' => 19.50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL005',
                'nama_kapal' => 'KM Bahari Kita',
                'jenis_kapal' => 'Fast Ferry',
                'operator_id' => 'OPR005',
                'kapasitas' => 300,
                'pelabuhan_asal' => 'Kalianget',
                'rute_aktif' => 'Kalianget → Kangean',
                'tanggal_registrasi' => '2018-11-05',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Fast ferry ke pulau terpencil',
                'nomor_registrasi' => 'REG-2018-005',
                'tahun_pembuatan' => 2016,
                'panjang_kapal' => 75.00,
                'lebar_kapal' => 16.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL006',
                'nama_kapal' => 'KMP Komodo',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR006',
                'kapasitas' => 250,
                'pelabuhan_asal' => 'Waingapu',
                'rute_aktif' => 'Waingapu → Ende',
                'tanggal_registrasi' => '2021-07-18',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Sangat Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Melayani NTT',
                'nomor_registrasi' => 'REG-2021-006',
                'tahun_pembuatan' => 2020,
                'panjang_kapal' => 98.00,
                'lebar_kapal' => 21.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL007',
                'nama_kapal' => 'KMP Komodo',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR007',
                'kapasitas' => 300,
                'pelabuhan_asal' => 'Sape',
                'rute_aktif' => 'Sape → Labuan Bajo',
                'tanggal_registrasi' => '2019-02-14',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Rute wisata Komodo',
                'nomor_registrasi' => 'REG-2019-007',
                'tahun_pembuatan' => 2017,
                'panjang_kapal' => 105.00,
                'lebar_kapal' => 22.50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL008',
                'nama_kapal' => 'KM Lambelu',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR008',
                'kapasitas' => 300,
                'pelabuhan_asal' => 'Kendari',
                'rute_aktif' => 'Kendari → Bau-Bau',
                'tanggal_registrasi' => '2020-05-22',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Cukup Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Melayani Sulawesi Tenggara',
                'nomor_registrasi' => 'REG-2020-008',
                'tahun_pembuatan' => 2019,
                'panjang_kapal' => 88.00,
                'lebar_kapal' => 19.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL009',
                'nama_kapal' => 'KM Sinabung',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR009',
                'kapasitas' => 250,
                'pelabuhan_asal' => 'Ambon',
                'rute_aktif' => 'Ambon → Sorong → Jayapura',
                'tanggal_registrasi' => '2018-09-30',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Rute Indonesia Timur',
                'nomor_registrasi' => 'REG-2018-009',
                'tahun_pembuatan' => 2015,
                'panjang_kapal' => 115.00,
                'lebar_kapal' => 24.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kapal_id' => 'KPL010',
                'nama_kapal' => 'KM Ciremai',
                'jenis_kapal' => 'Ferry',
                'operator_id' => 'OPR010',
                'kapasitas' => 250,
                'pelabuhan_asal' => 'Sorong',
                'rute_aktif' => 'Sorong → Waisai → Jayapura',
                'tanggal_registrasi' => '2021-12-01',
                'status_operasional' => 'Beroperasi',
                'status_kebersihan' => 'Sangat Bersih',
                'foto_kapal' => null,
                'keterangan_tambahan' => 'Kapal baru melayani Papua',
                'nomor_registrasi' => 'REG-2021-010',
                'tahun_pembuatan' => 2021,
                'panjang_kapal' => 120.00,
                'lebar_kapal' => 25.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('kapals')->insert($kapals);

        $this->command->info('✓ Kapal data seeded successfully!');
    }
}
